server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/education?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #数据库连接超时时间
      connection-timeout: 30000
      #连接池最大连接数，默认是10
      maximum-pool-size: 30
      #最小空闲连接数量
      minimum-idle: 10
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期
      max-lifetime: 6000
  redis:
    password: 123456
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
